<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<testsuites>
  <testsuite name="First Test Suite" timestamp="2024-11-20T05:26:28" tests="2" failures="1" time="3.238" file="cy-example/e2e/first.cy.js">
    <testcase name="First Test Suite visits google" time="0" classname="visits google" failure="true" error="true" success="false">
      <failure message="Timed out retrying after 4000ms: expected 'Google' to include 'Amazon'" type="AssertionError">AssertionError: Timed out retrying after 4000ms: expected 'Google' to include 'Amazon'
    at Context.eval (webpack:///./e2e/first.cy.js:4:15)</failure>
    </testcase>
    <testcase name="First Test Suite can search" time="3.238" classname="can search" failure="false" error="false" success="true"/>
  </testsuite>
  <testsuite name="Second Test Suite" timestamp="2024-11-20T05:26:40" tests="2" failures="0" time="4.33" file="cy-example/e2e/second.cy.js">
    <testcase name="Second Test Suite visits google" time="1.174" classname="visits google" failure="false" error="false" success="true"/>
    <testcase name="Second Test Suite can search" time="3.156" classname="can search" failure="false" error="false" success="true"/>
  </testsuite>
</testsuites>